### ISSUE TITLE
Support multiple CORS for chat/tracker

### ISSUE THREAD

**Issue by jontyk** [openline-ai/openline-oasis#101]
**Overview of the feature request and the problem you're looking to solve**
Currently I am unable to stage and test changes on a domain other than my production domain (such as *.vercel.app) as I cannot set more than one CORS allowed domain.

**Describe the solution you'd like**
Allow for multiple CORS addresses to be added to the oasis backend CORS allowed domain list.

**Additional context**
N/A

Thank you for your feature request!  We strive to make the product better every day, and your input helps!

**Comment by tsearle** [comment]
Wildcard domains are not allowed.

Please specify the precise domain you want to use

**Comment by jontyk** [comment]
https://staging-openline.vercel.app/ !!
