### ISSUE TITLE
bcc email address to capture email conversation

### ISSUE THREAD

**Issue by mattbr0wn** [openline-ai/openline-oasis#315]
As a user of CustomerOS, I want to be able to bcc emails I send in order to have the email conversation logged against the recipients profile in CustomerDB.

**Comment by gabriel0003** [comment]
I couldn't get gmail filters to forward outgoing messages. 
This makes this task more complicated

The solution is google script
https://script.google.com/ 
or 
google api - this will require most likely an endpoint on our side where google will send update on the send folder on gmail

**Comment by gabriel0003** [comment]
Close this with won't fix. Opened a different task for a different solution to the problem
https://github.com/openline-ai/openline-customer-os/issues/976
